# Generated by Django 4.2.2 on 2023-06-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team_24', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='internRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.EmailField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
