# Generated by Django 4.2.2 on 2023-06-10 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Team_24', '0002_internregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='hiringDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=20)),
                ('fullname', models.CharField(max_length=20)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Others'), (4, 'Prefer not to say')])),
                ('dob', models.DateField()),
                ('phonenumber', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=20)),
                ('internshiprole', models.IntegerField(choices=[(1, 'In-Person'), (2, 'Virtual')])),
                ('tellusaboutyourself', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_remark', models.CharField(default='', max_length=500)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_image/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
