# Generated by Django 4.2.2 on 2023-06-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team_24', '0003_hiringdetails_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('funds', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='hiringdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='login',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
